export default Object.freeze({
    USER_STORE: {
        AUTH_ACTION_REQUEST: 'AUTH_ACTION_REQUEST',
        AUTH_ACTION_SUCCESS: 'AUTH_ACTION_SUCCESS',
        AUTH_ACTION_ERROR: 'AUTH_ACTION_ERROR',
        CLEAR_USER_STORE_ERROR: 'CLEAR_AUTH_ERROR',
        LOGOUT_REQUEST: 'LOGOUT_ACTION_REQUEST',
        LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
    }
});