export default Object.freeze({
    USER_STORE: {
        AUTH_ACTION_REQUEST: 'AUTH_ACTION_REQUEST',
        AUTH_ACTION_SUCCESS: 'AUTH_ACTION_SUCCESS',
        AUTH_ACTION_ERROR: 'AUTH_ACTION_ERROR',
        CLEAR_USER_STORE_ERROR: 'CLEAR_AUTH_ERROR',
        LOGOUT_REQUEST: 'LOGOUT_ACTION_REQUEST',
        LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
    },
    USERS_DATA_STORE: {
        GET_USERS_REQUEST: 'GET_USERS_REQUEST',
        GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
        GET_USERS_ERROR: 'GET_USERS_ERROR',
        CHANGE_USER_DATA_REQUEST: 'CHANGE_USER_DATA_REQUEST',
        CHANGE_USER_DATA_SUCCESS: 'CHANGE_USER_DATA_SUCCESS',
        CHANGE_USER_DATA_ERROR: 'CHANGE_USER_DATA_ERROR',
        OPEN_USER_EDITING_FORM: 'OPEN_USER_EDITING_FORM',
        CLOSE_USER_EDITING_FORM: 'CLOSE_USER_EDITING_FORM',
        CLEAR_USERS_DATA_STORE_ERROR: 'CLEAR_USERS_DATA_STORE_ERROR',
    }
});